---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE)
```

```{r funcs, echo=F, include=F}
library(magrittr)
library(dplyr)
require(readxl)
require(viridis)
library(reactable)
library(htmltools)

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

normalize_col_vec <- function(df, col, value) {
  x <- df[[col]]
  min <- x %>% min()
  max <- x %>% max()
  res <- (value - min) / (max - min)
  res
}

pal_react <- viridis::magma(n = 5, begin = 0.6, end = 1) %>% make_color_pal(bias = 2)
```

```{r data, echo=F, include=F}
dir_proj <- '27-pep'
df <- file.path(dir_proj, 'ucl_matches.csv') %>% read_csv()
df

lines <-
  df %>% 
  mutate(
    team_w_1 = ifelse(g_h_1 < g_a_1, team_a_1, team_h_1),
    team_l_1 = ifelse(g_h_1 < g_a_1, team_h_1, team_a_1),
    g_w_1 = ifelse(g_h_1 < g_a_1, g_a_1, g_h_1),
    g_l_1 = ifelse(g_h_1 < g_a_1, g_h_1, g_a_1), 
    line_1 = case_when(
      g_h_1 == g_a_1 ~ sprintf('Draw %s-%s at %s', g_h_1, g_a_1, team_h_1), 
      TRUE ~ sprintf('%s wins %s-%s %s', team_w_1, g_w_1, g_l_1, ifelse(team_h_1 == team_w_1, 'at home', 'as visitor'))
    ),
    
    team_w_2 = ifelse(g_h_2 < g_a_2, team_a_2, team_h_2),
    team_l_2 = ifelse(g_h_2 < g_a_2, team_h_2, team_a_2),
    g_w_2 = ifelse(g_h_2 < g_a_2, g_a_2, g_h_2),
    g_l_2 = ifelse(g_h_2 < g_a_2, g_h_2, g_a_2), 
    line_2 = case_when(
      g_h_2 == g_a_2 ~ sprintf('Draw %s-%s at %s', g_h_2, g_a_2, team_h_2), 
      TRUE ~ sprintf('%s wins %s-%s %s', team_w_2, g_w_2, g_l_2, ifelse(team_h_2 == team_w_2, 'at home', 'as visitor'))
    ),
    
    line_ucl = sprintf('%s wins %s-%s%s', team_w, g_w, g_l, ifelse(is.na(penalties), '', penalties)),
    across(matches('^date'), list(dummy = ~str_sub(.x, 1, str_length(.x) -4) %>% paste0('2031') %>% lubridate::mdy())) # 
    # across(matches('^date'), lubridate::mdy)
  ) %>% 
  mutate(across(line_ucl, ~ifelse(season == '2019-20', '', .x))) %>% 
  select(season, matches('^date.*dummy'), line_ucl, line_1, line_2)
lines

cols <- c('team_h', )
cols_adj <- sprintf('%s_adj', cols)
# npg90 <- c(df[['npg90_change_perc']], df[['npg90_change_perc_adj']])
```

```{r df_react}
df_react <-
  df %>% 
  reactable::reactable(
    pagination = FALSE,
    compact = TRUE,
    borderless = TRUE,
    striped = FALSE,
    fullWidth = FALSE,
    
    # defaultSorted = 'rnk_adj',
    # defaultSortOrder = 'asc',
    defaultColGroup = colGroup(headerClass = 'group-header'),
    
    columnGroups = list(
      colGroup(name = 'Un-Adjusted', columns = cols),
      colGroup(name = 'Adjusted', columns = cols_adj),
      colGroup(name = 'Minutes', columns = sprintf('min_%s', c('domestic', 'ucl')))
    ),

    # Emphasize borders between groups when sorting by group
    rowClass = JS("
    function(rowInfo, state) {
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'group') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row.group !== nextRow.group) {
          return 'group-last'
        }
      }
    }"
    ),
    showSortIcon = FALSE,
    class = 'ranking-table',
    
    defaultColDef = colDef(
      class = 'cell', # glin
      headerClass = 'header' # , # glin
      # align = 'right', # tmock
      # minWidth = 100 # tmochk
    ),
    
    columns = list(

      player = colDef(
        name = 'Name',
        minWidth = 140,
        # maxWidth = 140,
        align = 'left',
        headerStyle = list(fontWeight = 700), # glin
        cell = function(value) {
          div(
            class = 'player',
            div(class = 'player-name', value)
          )
        }
      ),

      domestic = colDef(
        name = 'Domestic'
      ),

      ucl = colDef(
        name = 'UCL',
        maxWidth = 60
      ),

      npg90_change_perc = colDef(
        name = 'Change',
        maxWidth = 80,
        style = function(value) {
          value_normal <- normalize_col_vec(df, 'npg90_change_perc', value)
          pal <- pal_react(value_normal)
          list(color = '#111', background = pal)
        },
        cell = JS('function(cellInfo) {return cellInfo.value + "%"}'),
        class = 'border-left'
      ),

      rnk = colDef(
        name = 'Rank',
        # class = 'border-right',
        maxWidth = 60
      ),

      domestic_adj = colDef(
        name = 'Domestic'
      ),

      ucl_adj = colDef(
        name = 'UCL',
        maxWidth = 60
      ),

      npg90_change_perc_adj = colDef(
        name = 'Change',
        maxWidth = 80,
        style = function(value) {
          value_normal <- normalize_col_vec(df, 'npg90_change_perc_adj', value)
          pal <- pal_react(value_normal)
          list(color = '#111', background = pal)
        },
        cell = JS('function(cellInfo) {return cellInfo.value + "%"}'),
        class = 'border-left'
      ),

      rnk_adj = colDef(
        name = 'Rank',
        maxWidth = 60
      ),
      
      min_domestic = colDef(
        name = 'Domestic',
        cell = JS('function(cellInfo) {return cellInfo.value + "k"}'),
      ),
      
      min_ucl = colDef(
        name = 'UCL',
        cell = JS('function(cellInfo) {return cellInfo.value + "k"}'),
        maxWidth = 60
      )
    )
  )
```

```{r divs, echo=F}
div(
  class = 'rankings',
  div(
    class = 'title',
    h2('Non-Penalty Goals Per 90 Minutes, Adjusted for Competition'),
  ),
  df_react,
  tags$span('2020 UCL statistics not included'),
  tags$br(),
  tags$span('Table: @TonyElHabr | Data: 21stClub | Inspiration: Greg Lin & @thomas_mock')
)
```
