---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE)
```

```{r funcs, echo=F, include=F}
library(magrittr)
library(dplyr)
require(readxl)
require(viridis)
library(reactable)
library(htmltools)

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

normalize_col_vec <- function(df, col, value) {
  x <- df[[col]]
  min <- x %>% min()
  max <- x %>% max()
  res <- (value - min) / (max - min)
  res
}

pal_react <- viridis::magma(n = 5, begin = 0.6, end = 1) %>% make_color_pal(bias = 2)
```

```{r data, echo=F, include=F}
df <- 
  here::here('data-raw', '04', '04_ucl_npg90_adj.xlsx') %>% 
  readxl::read_excel() %>% 
  mutate(across(matches('^min'), ~{round(.x / 1000, 1)}))
df
cols <- c('domestic', 'ucl', 'npg90_change_perc', 'rnk')
cols_adj <- sprintf('%s_adj', cols)
# npg90 <- c(df[['npg90_change_perc']], df[['npg90_change_perc_adj']])
```

```{r df_react}
df_react <-
  df %>% 
  reactable::reactable(
    pagination = FALSE,
    compact = TRUE,
    borderless = TRUE,
    striped = FALSE,
    fullWidth = FALSE,
    
    defaultSorted = 'rnk_adj',
    defaultSortOrder = 'asc',
    defaultColGroup = colGroup(headerClass = 'group-header'),
    
    columnGroups = list(
      colGroup(name = 'Un-Adjusted', columns = cols),
      colGroup(name = 'Adjusted', columns = cols_adj),
      colGroup(name = 'Minutes', columns = sprintf('min_%s', c('domestic', 'ucl')))
    ),

    # Emphasize borders between groups when sorting by group
    rowClass = JS("
    function(rowInfo, state) {
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'group') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row.group !== nextRow.group) {
          return 'group-last'
        }
      }
    }"
    ),
    showSortIcon = FALSE,
    class = 'ranking-table',
    
    defaultColDef = colDef(
      class = 'cell', # glin
      headerClass = 'header' # , # glin
      # align = 'right', # tmock
      # minWidth = 100 # tmochk
    ),
    
    columns = list(

      player = colDef(
        name = 'Name',
        minWidth = 140,
        # maxWidth = 140,
        align = 'left',
        headerStyle = list(fontWeight = 700), # glin
        cell = function(value) {
          div(
            class = 'player',
            div(class = 'player-name', value)
          )
        }
      ),

      domestic = colDef(
        name = 'Domestic'
      ),

      ucl = colDef(
        name = 'UCL',
        maxWidth = 60
      ),

      npg90_change_perc = colDef(
        name = 'Change',
        maxWidth = 80,
        style = function(value) {
          value_normal <- normalize_col_vec(df, 'npg90_change_perc', value)
          pal <- pal_react(value_normal)
          list(color = '#111', background = pal)
        },
        cell = JS('function(cellInfo) {return cellInfo.value + "%"}'),
        class = 'border-left'
      ),

      rnk = colDef(
        name = 'Rank',
        # class = 'border-right',
        maxWidth = 60
      ),

      domestic_adj = colDef(
        name = 'Domestic'
      ),

      ucl_adj = colDef(
        name = 'UCL',
        maxWidth = 60
      ),

      npg90_change_perc_adj = colDef(
        name = 'Change',
        maxWidth = 80,
        style = function(value) {
          value_normal <- normalize_col_vec(df, 'npg90_change_perc_adj', value)
          pal <- pal_react(value_normal)
          list(color = '#111', background = pal)
        },
        cell = JS('function(cellInfo) {return cellInfo.value + "%"}'),
        class = 'border-left'
      ),

      rnk_adj = colDef(
        name = 'Rank',
        maxWidth = 60
      ),
      
      min_domestic = colDef(
        name = 'Domestic',
        cell = JS('function(cellInfo) {return cellInfo.value + "k"}'),
      ),
      
      min_ucl = colDef(
        name = 'UCL',
        cell = JS('function(cellInfo) {return cellInfo.value + "k"}'),
        maxWidth = 60
      )
    )
  )
```

```{r divs, echo=F}
div(
  class = 'rankings',
  div(
    class = 'title',
    h2('Non-Penalty Goals Per 90 Minutes, Adjusted for Competition'),
  ),
  df_react,
  tags$span('2020 UCL statistics not included'),
  tags$br(),
  tags$span('Table: @TonyElHabr | Data: 21stClub | Inspiration: Greg Lin & @thomas_mock')
)
```

```{r gfonts, echo=F}
tags$link(href = 'https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback', rel = 'stylesheet')
# tags$link(href = 'https://fonts.googleapis.com/css2?family=Fira+Mono&family=IBM+Plex+Mono&display=swap', rel = 'stylesheet')
# tags$link(href = 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&display=swa', rel = 'stylesheet')
```

```{css styles, echo=F}
.rankings {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
}

.title {
  margin: 18px 0;
  font-size: 16px;
}

.title h2 {
  font-size: 20px;
  font-weight: 600;
}

.rankings-table {
  margin-bottom: 20px;
}

/* Align header text to the bottom */
.header,
.group-header {
  display: flex;
  flex-direction: column;
  //justify-content: flex-end;
}

.header {
  border-bottom-color: #555;
  font-size: 14px;
  font-weight: 400;
  text-transform: uppercase;
}

/* Highlight headers when sorting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #eee;
}

.border-left {
  border-left: 2px solid #555;
}

.border-right {
  border-right: 2px solid #555;
}

/* Use box-shadow to create row borders that appear behind vertical borders */
.cell {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
}

.group-last .cell {
  box-shadow: inset 0 -2px 0 #555;
}

.player {
  display: flex;
  align-items: baseline;
}

.player-name {
  font-size: 14px;
  font-weight: 700;
}

.group {
  font-size: 14px;
}

.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 16px;
  line-height: 30px;
  white-space: pre;
}
```

```{r}
htmltools::save_html(
```


